-- Seeds photo_overrides with every destination/dining-venue photo already in mockData.js, so the Photo Library starts showing real current values instead of empty slots.

insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_1', 'Destination', 'Champagne Reef', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Scotts_Head%2C_Dominica_014.jpg/1280px-Scotts_Head%2C_Dominica_014.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_2', 'Destination', 'Boiling Lake', 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Dominica_boiling_lake.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_3', 'Destination', 'Trafalgar Falls', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Trafalgar_Falls_at_Morne_Trois_Pitons_National_Park.jpg/1280px-Trafalgar_Falls_at_Morne_Trois_Pitons_National_Park.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_4', 'Destination', 'Morne Trois Pitons National Park', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Morne_Trois_Pitons_National_Park%2C_Dominica_-_jungle.jpg/1280px-Morne_Trois_Pitons_National_Park%2C_Dominica_-_jungle.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_5', 'Destination', 'Emerald Pool', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Emerald_Pool%2C_Dominica.jpg/1280px-Emerald_Pool%2C_Dominica.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_6', 'Destination', 'Whale Watching, Roseau', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Baleine_Ile_de_la_Dominique.jpg/1280px-Baleine_Ile_de_la_Dominique.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_7', 'Destination', 'Old Roseau Market & Waterfront', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Produce_Market%2C_Roseau%2C_Dominica.jpg/1280px-Produce_Market%2C_Roseau%2C_Dominica.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_8', 'Destination', 'Ti Kwen Glo Cho Hot Springs', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Dominica%2C_Karibik_-_Laudat_-_Wotten_Waven_%E2%80%93_Fond_Cani_-_panoramio.jpg/1280px-Dominica%2C_Karibik_-_Laudat_-_Wotten_Waven_%E2%80%93_Fond_Cani_-_panoramio.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_9', 'Destination', 'Canyoning at Titou Gorge', 'https://justgodominica.com/wp-content/uploads/2020/01/Titou-Gorge_dominica-005-400x284.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_10', 'Destination', 'Cabrits National Park & Fort Shirley', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Fort_Shirley%2C_Dominica%2C_2026.jpg/1280px-Fort_Shirley%2C_Dominica%2C_2026.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_11', 'Destination', 'Indian River, Portsmouth', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Indian_River_in_Portsmouth%2C_Dominica.jpg/1280px-Indian_River_in_Portsmouth%2C_Dominica.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_12', 'Destination', 'Middleham Falls', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Middleham_Falls_at_Morne_Trois_Pitons_National_Park.jpg/1280px-Middleham_Falls_at_Morne_Trois_Pitons_National_Park.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_13', 'Destination', 'Freshwater Lake', 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Freshwater_Lake%2C_Dominica.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_14', 'Destination', 'Kalinago Territory', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Carib_Territory_%28Dominica%29.jpg/1280px-Carib_Territory_%28Dominica%29.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_15', 'Destination', 'Syndicate Nature Trail & Parrot Reserve', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Amazona_imperialis_-Roseau_-Dominica_-aviary-6a.jpg/1280px-Amazona_imperialis_-Roseau_-Dominica_-aviary-6a.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_16', 'Destination', 'Mero Beach', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/MERO_BEACH%2C_DOMINICA.jpg/1280px-MERO_BEACH%2C_DOMINICA.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_17', 'Destination', 'Soufriere Village & Sulphur Springs', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Soufri%C3%A8re_Bay%2C_Dominica_008.JPG/1280px-Soufri%C3%A8re_Bay%2C_Dominica_008.JPG') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_18', 'Destination', 'Bush Rum Tasting', 'https://cdn.discoverdominica.com/production/20200218085528-dsc-23064.jpeg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_19', 'Destination', 'Scotts Head (Cachacrou)', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Scotts_Head_Dominica_1.jpg/1280px-Scotts_Head_Dominica_1.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_20', 'Destination', 'Boeri Lake', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Boeri_Lake.jpg/1280px-Boeri_Lake.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('destination:d_21', 'Destination', 'Wavine Cyrique', 'https://i0.wp.com/www.rosalieforest.com/wp-content/uploads/2015/05/wavine-cyrique-21.jpg?w=1872') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('dining:v_1', 'Dining Venue', 'Tide & Table', 'https://symphony.cdn.tambourine.com/_fusion/ocean-oasis/media/oceanedgedevelopment-homepage-gallery-01-69028ae57d28a.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('dining:v_2', 'Dining Venue', 'Oasis Terrace', 'https://symphony.cdn.tambourine.com/_fusion/ocean-oasis/media/oceanedgedevelopment-homepage-gallery-02-69028ae71481e.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('dining:v_3', 'Dining Venue', 'Horizon Bar', 'https://symphony.cdn.tambourine.com/_fusion/ocean-oasis/media/oceanedgedevelopment-homepage-gallery-03-69028ae892712.jpg') on conflict (slot_key) do nothing;
insert into public.photo_overrides (slot_key, category, label, image_url) values ('dining:v_4', 'Dining Venue', 'In-Room Dining', 'https://symphony.cdn.tambourine.com/_fusion/ocean-oasis/media/oceanedgedevelopment-homepage-gallery-04-69028ae9e7bce.jpg') on conflict (slot_key) do nothing;
